#cloud-config

coreos:
  etcd:
    name: 4dd7ed89c8a942a68a3a0f9502e58f40
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
    # The number needs to be at least: one + peers allowed to particiate election
    cluster-active-size: 9
    # If this is the first in the cluster, the etcd would fail. 
    # Work aroud is to modify /etc/systemd/system/etcd.service.d/20-cloudinit.conf to 
    # only leave the first server's IP in peer list.
    peers: "10.0.2.50:7001,10.0.2.100:7001,10.0.2.150:7001"
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      mask: true
      
