#cloud-config

# Workers cloud-config: run fleetd only
coreos:
  etcd2:
    proxy: on
  fleet:
    public-ip: $private_ipv4
    metadata: "disk=ssd,env=coreos-cluster,platform=ec2,provider=aws,region=us-west-2,role=worker"
  update:
    reboot-strategy: off
  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 60-initial-cluster.conf
          content: |
            [Service]
            EnvironmentFile=/etc/sysconfig/initial-cluster
    - name: fleet.service
      command: start
