#cloud-config

coreos:
  fleet:
    public-ip: $private_ipv4
    metadata: "platform=ec2,provider=aws,region=us-west-2,disk=ssd,role=dockerhub"
    etcd_servers: "http://10.0.2.50:4001,http://10.0.2.100:4001,http://10.0.2.150:4001"
  units:
    - name: etcd.service
      mask: true
    - name: fleet.service
      command: reload-or-restart
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
          [Unit]
          Description=Docker Socket for the API
          
          [Socket]
          ListenStream=2375
          Service=docker.service
          BindIPv6Only=both
          
          [Install] 
          WantedBy=sockets.target
