#cloud-config

coreos:
  fleet:
    public-ip: $private_ipv4
    metadata: "platform=ec2,provider=aws,region=us-west-2,disk=ssd,role=core"
    etcd_servers: "http://10.0.2.50:4001,http://10.0.2.100:4001,http://10.0.2.150:4001"
  update:
    reboot-strategy: off
  units:
    - name: etcd.service
      mask: true
    - name: fleet.service
      command: reload-or-restart
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
          [Unit]
          Description=Docker Socket for the API
          
          [Socket]
          ListenStream=2375
          Service=docker.service
          BindIPv6Only=both
          
          [Install] 
          WantedBy=sockets.target    
    - name: format-opt-data.service
      command: start
      content: |
        [Unit]
        Description=Formats opt data drive
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        Environment="LABEL=opt-data"
        Environment="DEV=/dev/xvdc"
        ExecStart=-/bin/bash -c "if ! findfs LABEL=$LABEL > /tmp/label.$LABEL; then  wipefs -a -f $DEV && mkfs.ext4 -F -L $LABEL $DEV && echo wiped; fi" 
    - name: opt-data.mount
      command: start
      content: |
        [Unit]
        Description=Mount data to /opt/data
        Requires=format-opt-data.service
        After=format-opt-data.service
        [Mount]
        What=/dev/xvdc
        Where=/opt/data
        Type=ext4

